from django.conf.urls import include,url
from . import views

urlpatterns = [
	url(r'^signin/', views.signin, name='signin'),
	url(r'^signup/', views.signup, name='signup'),
	url(r'^signout/', views.signout, name='signout'),
	url(r'^home/', views.home, name='home'),
	url(r'^about/', views.about, name='about'),
	url(r'^learn/', views.learn, name='learn'),
	url(r'^blog/', views.blog, name='blog'),
	url(r'^snippet/', views.snippet, name='snippet'),
	url(r'^contact/', views.contact_form, name='contact'),
	url(r'^thankyou/(?P<ty_id>\d+)$', views.thankyou, name='thankyou'),
	url(r'^home_add_form/', views.home_add_form, name='homeaddform'),
	url(r'^home_edit_form/(?P<home_id>\d+)$', views.home_edit_form, name='homeeditform'),
	url(r'^about_add_form/', views.about_add_form, name='aboutaddform'),
	url(r'^about_edit_form/(?P<about_id>\d+)$', views.about_edit_form, name='abouteditform'),
	url(r'^snippet_add_form/', views.snippet_add_form, name='snippetaddform'),
	url(r'^snippet_edit_form/(?P<snippet_id>\d+)$', views.snippet_edit_form, name='snippeteditform'),
	url(r'^learn_add_form/', views.learn_add_form, name='learnaddform'),
	url(r'^learn_edit_form/(?P<learn_data_id>\d+)$', views.learn_edit_form, name='learneditform'),
	url(r'^snippet_topics_data_view/(?P<snippet_data_id>\d+)$', views.snippet_topics_view, name='snippetview'),
	url(r'^snippet_topics_add_form/(?P<snippet_topics_id>\d+)$', views.snippet_topics_add_form, name='snippettopicsaddform'),
	url(r'^snippet_topics_edit_form/(?P<snippet_data_id>\d+)$', views.snippet_topics_edit_form, name='snippettopicseditform'),
	url(r'^snippet_topics/(?P<snippet_topics_id>\d+)$', views.snippet_topics, name='snippettopics'),
	url(r'^learn_topics_data_view/(?P<learn_data_id>\d+)$', views.learn_topics_view, name='learnview'),
	url(r'^learn_topics_add_form/(?P<learn_topics_id>\d+)$', views.learn_topics_add_form, name='learntopicsaddform'),
	url(r'^learn_topics_edit_form/(?P<learn_data_id>\d+)$', views.learn_topics_edit_form, name='learntopicseditform'),
	url(r'^learn_topics/(?P<learn_topics_id>\d+)$', views.learn_topics, name='learntopics'),
	url(r'^blog_topics_add_form/', views.blog_topics_add_form, name='blogtopicsaddform'),
	url(r'^blog_topics_edit_form/(?P<blog_id>\d+)$', views.blog_topics_edit_form, name='blogtopicseditform'),
	url(r'^blog_topics/(?P<blog_id>\d+)$', views.blog_topics, name='blogtopics'),
	url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    ]
