# Generated by Django 2.0.5 on 2019-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblBlog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_datetime', models.DateTimeField(blank=True, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_content', models.TextField(blank=True, null=True)),
                ('blog_like', models.IntegerField(blank=True, db_column='blog_Like', null=True)),
                ('blog_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBlogComments',
            fields=[
                ('blog_comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_comments_datetime', models.DateTimeField(blank=True, null=True)),
                ('blog_comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_blog_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBlogGvp',
            fields=[
                ('blog_gvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_gvp_datetime', models.DateTimeField(blank=True, null=True)),
                ('blog_gif', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_video', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_pics', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_blog_gvp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLearnData',
            fields=[
                ('learn_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_data_datetime', models.DateTimeField(blank=True, null=True)),
                ('learn_data_like', models.IntegerField(blank=True, db_column='learn_data_Like', null=True)),
                ('learn_data_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_data', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_data_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_learn_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLearnDataComments',
            fields=[
                ('learn_data_comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_data_comments_datetime', models.DateTimeField(blank=True, null=True)),
                ('learn_data_comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_learn_data_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLearnDataGvp',
            fields=[
                ('learn_data_gvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_data_gvp_datetime', models.DateTimeField(blank=True, null=True)),
                ('learn_data_gif', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_data_video', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_data_pics', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_learn_data_gvp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLearnTopics',
            fields=[
                ('learn_topics_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_topics_datetime', models.DateTimeField(blank=True, null=True)),
                ('learn_topics', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_topics_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_topics_coverpage_img', models.CharField(blank=True, max_length=255, null=True)),
                ('learn_topics_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_learn_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPublish',
            fields=[
                ('publish_id', models.AutoField(primary_key=True, serialize=False)),
                ('input', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_publish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSnippetData',
            fields=[
                ('snippet_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet_data_datetime', models.DateTimeField(blank=True, null=True)),
                ('snippet_data_like', models.IntegerField(blank=True, db_column='snippet_data_Like', null=True)),
                ('snippet_data_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet_data_description', models.TextField(blank=True, null=True)),
                ('snippet_data_expire', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_snippet_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSnippetDataGvp',
            fields=[
                ('snippet_data_gvp_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet_data_gvp_datetime', models.DateTimeField(blank=True, null=True)),
                ('snippet_data_gif', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet_data_video', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet_data_pics', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_snippet_data_gvp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSnippetTopics',
            fields=[
                ('snippet_topics_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet_topics_datetime', models.DateTimeField(blank=True, null=True)),
                ('snippet_topics', models.CharField(blank=True, max_length=100, null=True)),
                ('snippet_topics_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet_topics_coverpage_img', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet_topics_description', models.TextField(blank=True, null=True)),
                ('snippet_topics_expire', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_snippet_topics',
                'managed': False,
            },
        ),
    ]
