# Generated by Django 2.0.5 on 2019-03-29 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAbout',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_datetime', models.DateTimeField(default=datetime.datetime(2019, 3, 29, 20, 26, 13, 929092))),
                ('about_pics', models.FileField(blank=True, null=True, upload_to='about/')),
                ('about_content', models.CharField(blank=True, max_length=255, null=True)),
                ('about_content_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_about',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblHome',
            fields=[
                ('home_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_datetime', models.DateTimeField(default=datetime.datetime(2019, 3, 29, 20, 26, 13, 929092))),
                ('home_pics', models.FileField(blank=True, null=True, upload_to='home/')),
                ('home_content', models.CharField(blank=True, max_length=255, null=True)),
                ('home_content_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_home',
                'managed': False,
            },
        ),
    ]
