# Generated by Django 2.0.5 on 2019-03-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tblabout_tblhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAboutExpert',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('expert_datetime', models.DateTimeField(blank=True, null=True)),
                ('expert_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_skill', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_avtar', models.CharField(blank=True, max_length=255, null=True)),
                ('expert_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_about_expert',
                'managed': False,
            },
        ),
    ]
