# Generated by Django 2.0.5 on 2019-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tblaboutexpert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblQueries',
            fields=[
                ('queries_id', models.AutoField(db_column='Queries_id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='Datetime')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('subject', models.CharField(db_column='Subject', max_length=255)),
                ('message', models.TextField(db_column='Message')),
            ],
            options={
                'db_table': 'tbl_Queries',
                'managed': False,
            },
        ),
    ]
