# Generated by Django 2.0.5 on 2019-04-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tblqueries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblblog',
            options={},
        ),
    ]
