# Generated by Django 2.0.5 on 2019-04-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190422_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblblog',
            options={'managed': False},
        ),
    ]
