# Generated by Django 2.0.5 on 2019-04-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190422_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblblog',
            options={'managed': True},
        ),
    ]
