# Generated by Django 2.0.5 on 2019-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190422_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblLearnLike',
            fields=[
                ('learn_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_like_datetime', models.DateTimeField(blank=True, null=True)),
                ('learn_like_field', models.IntegerField(blank=True, db_column='learn_like_', null=True)),
            ],
            options={
                'db_table': 'tbl_learn_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSnippetLike',
            fields=[
                ('snippet_like_id', models.AutoField(primary_key=True, serialize=False)),
                ('snippet_like_datetime', models.DateTimeField(blank=True, null=True)),
                ('snippet_like', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_snippet_like',
                'managed': False,
            },
        ),
    ]
